--
-- PostgreSQL database dump
--

\restrict dSh1fIY8s2AlkE5wfTzRkuYCryfesflmfAYbcK1QkUInsABToAgoYjg3llKvsq0

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-08 23:05:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 845 (class 1247 OID 84634)
-- Name: account_type; Type: TYPE; Schema: public; Owner: risso64766
--

CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);


ALTER TYPE public.account_type OWNER TO risso64766;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 84641)
-- Name: account; Type: TABLE; Schema: public; Owner: risso64766
--

CREATE TABLE public.account (
    account_id integer NOT NULL,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type public.account_type DEFAULT 'Client'::public.account_type NOT NULL
);


ALTER TABLE public.account OWNER TO risso64766;

--
-- TOC entry 216 (class 1259 OID 84647)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: risso64766
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 84648)
-- Name: classification; Type: TABLE; Schema: public; Owner: risso64766
--

CREATE TABLE public.classification (
    classification_id integer NOT NULL,
    classification_name character varying NOT NULL
);


ALTER TABLE public.classification OWNER TO risso64766;

--
-- TOC entry 218 (class 1259 OID 84653)
-- Name: classification_classification_id_seq; Type: SEQUENCE; Schema: public; Owner: risso64766
--

ALTER TABLE public.classification ALTER COLUMN classification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classification_classification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 84654)
-- Name: inventory; Type: TABLE; Schema: public; Owner: risso64766
--

CREATE TABLE public.inventory (
    inv_id integer NOT NULL,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL
);


ALTER TABLE public.inventory OWNER TO risso64766;

--
-- TOC entry 220 (class 1259 OID 84659)
-- Name: inventory_inv_id_seq; Type: SEQUENCE; Schema: public; Owner: risso64766
--

ALTER TABLE public.inventory ALTER COLUMN inv_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3264 (class 2606 OID 84661)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: risso64766
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- TOC entry 3266 (class 2606 OID 84663)
-- Name: classification classification_pk; Type: CONSTRAINT; Schema: public; Owner: risso64766
--

ALTER TABLE ONLY public.classification
    ADD CONSTRAINT classification_pk PRIMARY KEY (classification_id);


--
-- TOC entry 3268 (class 2606 OID 84665)
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: risso64766
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (inv_id);


--
-- TOC entry 3269 (class 2606 OID 84666)
-- Name: inventory fk_blassification; Type: FK CONSTRAINT; Schema: public; Owner: risso64766
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_blassification FOREIGN KEY (classification_id) REFERENCES public.classification(classification_id) ON UPDATE CASCADE;


--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO risso64766;


-- Completed on 2025-10-08 23:05:27

--
-- PostgreSQL database dump complete
--

\unrestrict dSh1fIY8s2AlkE5wfTzRkuYCryfesflmfAYbcK1QkUInsABToAgoYjg3llKvsq0


-- LAST THING TO RUN IN REBUILD.SQL

UPDATE public.inventory SET inv_description = REPLACE(inv_description,'small interiors','a huge interior') WHERE inv_id = 10;

UPDATE public.inventory SET inv_image = REPLACE(inv_image,'/images','images/vehicles'), inv_thumbnail = REPLACE(inv_thumbnail,'/images','/images/vehicles');